### ISSUE TITLE
Let members submit as their own account.

### ISSUE THREAD

**Issue by gint271** [team2517/2014FRC#1]
Eric needs about 30 minutes to get the programming laptop to let us do this.

**Comment by admalledd** [comment]
Note: I will be be adding the .bat file template here to the repo as well so that we can reference them in future years (or whatever).

Notes to myself: 

git uses `$USER` that is grabbed from the windows env BEFORE `/bin/bash` is called, hence a .bat is required. this .bat will also be loading a custom `.profile` for each user as well.

sample setx commands from my .bat file (added at lines 23 of `git-bash.bat`):

```
rem change username (and therefore "/home/$USER/" as well) 
set USER=admalledd
set LOGNAME=admalledd
set USERNAME=admalledd
```
