### ISSUE TITLE
Swerve code function

### ISSUE THREAD

**Issue by gint271** [team2517/2014FRC#21]
So both teleop and auto call that function.

**Comment by tylerscheuble** [comment]
I have done this, and used the function to update the motors in the form of a for loop.

**Comment by admalledd** [comment]
That was not exactly what I was meaning... what I was meaning was break out the swerve code entirely into its own function, so that we do a `updateSwerve(&leftStickVec,phi)` once per autoloop or teleop loop. (note: I forget how to pass structs around, but you get the idea)

Thus we would instead have:

```

if(moduleFlag && !calibrating)
{
    moduleFlag = false;
    /*SNIP-- getting and setting `leftStickVec` and `phi` 
    or is that somewhere else once we move things around?*/
    updateSwerve(&leftStickVec,phi);
}

```

So that if we wanted to manually force some direction or such we would just create a fake (or change the current) `leftStickVec` and `phi`

**Comment by tylerscheuble** [comment]
Provided in next year's code.
