### ISSUE TITLE
Catching Pneumatics

### ISSUE THREAD

**Issue by gint271** [team2517/2014FRC#3]
Need to run the compressor and choose buttons to open and close solenoids.

**Comment by admalledd** [comment]
Question for drivers: should we have the buttons "re-mappable"? (use `#define`'s ect ect in our case...)

by the time we make it to competition (or any serious driving!) we will want to lock the control map down so that drivers will stop having to re-learn the controls (even if it might be more comfortable, muscle memory is very important!)

**Comment by tylerscheuble** [comment]
Idea scrapped. Closing.
