### ISSUE TITLE
Look into a co-processor to the robot for vision

### ISSUE THREAD

**Issue by gint271** [team2517/2014FRC#7]
I'm not sure how to start doing this, but Eric seems to know.

**Comment by admalledd** [comment]
(updated/changed title: we want to look into how to do it and document it before we get to the point of actually seeing if we want it at all)

So, some questions and my basic answers (or lack thereof):
- Processor? I think the best answer here for ease of use is going ot be a raspberry PI due to being powered over 5v, is less than 5w of power ect ect.
- Communication? how do we get data back and forth from the co-processor? for the RPI we can just use ethernet/tcp to the CRIO if I understand the rules correctly.
- Camera data? My thought is that if we take the time to use a co-processor then we should make sure its USB compatible. then we can simply use USB webcams (yes multiple!)
- Rules? what do we need to know about powering this? rules about communications? many things need clarifications, I am willing to bet that someone on cheif delphi has already answered them we just need to find it...

Some other things that I forget. will come back later

**Comment by tylerscheuble** [comment]
Ran out of time; closing.
